### ISSUE TITLE
Flow port has no INTO-CPS property

### ISSUE THREAD

**Issue by XinGong-cloud** [INTO-CPS-Association/training#9]
I try to reproduct the tutorials of SysML for Co-Simualtion. And at step 9, "On the INTO-CPS property view , change
Type to ‘PType :: Real’, and Direction to ‘Out’." I find no valid property found in the INTO-CPS tab. And when I double clicked on the flow port icon, some errors happened, like"Internal error Reason: org.eclipse.swt.SWTException: Failed to execute runnable(org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException)".
What i did for using INTOCPS module extension? 
I cannot find INTO-CPS 1.6.00.jmdac file on the internet. Also I cannot use the INTO-CPS downloader manager to download file. So I package the INTO-CPS project from github(https://github.com/INTO-CPS-Association/sysml-profile). And I used maven to package project(my jdk is 32bit). A version error happened, so I just modify like that"<artifactId>sysmlarchitect</artifactId> <version>3.9.01</version>" to "<artifactId>sysmlarchitect</artifactId>
<version>3.9.00</version>" inside the [sysml-profile](https://github.com/INTO-CPS-Association/sysml-profile)/pom.xml.
And it seems that intocps-1.6.00.jmdac file can be generated in the project target folder. I just add the module into modelio 4.0.1. And it shows compatible.
Could anyone help me to solve this problem?

**Comment by XinGong-cloud** [comment]
Add Modelio log:

2022-11-17 13:56:26,532 ERROR .m.m.propertytab - null

java.lang.NullPointerException: null
	at org.modelio.module.intocps.utils.ModelsUtils.getPType(ModelsUtils.java:192)
	at org.modelio.module.intocps.utils.ModelsUtils.getValueTypes(ModelsUtils.java:206)
	at org.modelio.module.intocps.propertypage.FlowPortPropertyPage.<init>(FlowPortPropertyPage.java:63)
	at org.modelio.module.intocps.propertypage.INTOCPSPropertyManager.update(INTOCPSPropertyManager.java:273)
	at org.modelio.module.intocps.propertypage.INTOCPSPropertyPage.update(INTOCPSPropertyPage.java:90)
	at org.modelio.module.propertytab.model.ModulePropertyModel.<init>(ModulePropertyModel.java:66)
	at org.modelio.module.propertytab.propertytab.ModulePanelProvider.setInput(ModulePanelProvider.java:203)
	at org.modelio.module.propertytab.propertytab.ModulePropertyView.update(ModulePropertyView.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by clagms** [comment]
@etiennebrosse can you look into this? It seems an eclipse related issue.

@XinGong-cloud thank you very much for reporting this. In the past, the translation from sysml to the into-cps configuration files has been difficult, due to the many technologies involved. Can you work around this in the meantime? Are you able to setup a co-simulation without the use of sysml?

Thanks!

**Comment by XinGong-cloud** [comment]
> 

Reason is UID of PType is not compatible. Change UID of PType can fix that problem. 
Solution：
1）Print all elements in your project using 
` ArrayList<Package> pTypeLibraryRoot = (ArrayList<Package>) INTOCPSModule.getInstance().getModuleContext().getModelingSession().findByClass(org.modelio.metamodel.uml.statik.Package.class);`
You will find the UID of PType according to your specific Modelio version:
For my situation, 'PType'{c6a749b8-d39b-4bb9-8a0f-f7483381a775} Standard.Package.
2) Replace the UID instead of old one.
`org.modelio.metamodel.uml.statik.Package pTypeLibraryRoot = INTOCPSModule.getInstance().getModuleContext().getModelingSession().findElementById(org.modelio.metamodel.uml.statik.Package.class, "c6a749b8-d39b-4bb9-8a0f-f7483381a775");`
3) Maven install project again. 
A new jmadc file can be imported into Modelio correctly.
